CREATE TABLE IF NOT EXISTS settings (
  username VARCHAR(32) NOT NULL UNIQUE,
  catchPaste TINYINT(1) NOT NULL DEFAULT 1,
  use12Hours TINYINT(1) NOT NULL DEFAULT 0,
  lang CHAR(5),
  PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS migrations (
  revision TINYINT UNSIGNED NOT NULL UNIQUE,
  executedOn DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (revision)
);
