name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  install:
    name: Setup and quick checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          install-command: yarn install --frozen-lockfile
        env:
          CI: 1

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          install-command: yarn install --frozen-lockfile

      - name: Unit tests
        run: yarn test:unit

  e2e:
    name: End to End tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          install-command: yarn install --frozen-lockfile

      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          build: npx cypress info
          command: yarn test:e2e:rec
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: videos
          path: cypress/videos
